Data dataObj;
String objFileName = "pointcloud";
String objFilePath = "scripts";
String objFileType = "obj";
boolean useColors = true;
boolean useNormals = false;
PVector normal = new PVector(1,0,0);

void objMain() {
  objBegin();
  for (int i=0;i<voxel.length;i++) {
    for (int j=0;j<voxel[i].length;j++) {
      for (int k=0;k<voxel[i][j].length;k++) {
        if (voxel[i][j][k].drawMe) {
          String s = "v " + -voxel[i][j][k].p.x + " " + -voxel[i][j][k].p.y + " " + voxel[i][j][k].p.z;
          
          if (useColors) {
            // https://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files
            float[] c = normalizeRgb(voxel[i][j][k].c);
            s += " " + c[0] + " " + c[1] + " " + c[2];
          }
          
          if (useNormals) {
            dataObj.add("vn " + normal.x + " " + normal.y + " " + normal.z);
          }
          
          dataObj.add(s);
        }
      }
    }
  }
  objEnd();
}



//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void objBegin() {
  dataObj = new Data();
  dataObj.beginSave();
  //dataObj.add("####");
  //dataObj.add("#");
  //dataObj.add("# OBJ file generated by Meshlab");
  //dataObj.add("#");
  dataObj.add("####");
  //dataObj.add("# Object render_shot1_12.obj");
  dataObj.add("#");
  dataObj.add("# Vertices: "+ countVertices());
  dataObj.add("# Faces: 0");
  dataObj.add("#");
  dataObj.add("####");
}

void objEnd() {
  dataObj.add("# "+ countVertices() +" vertices, 0 vertex normals");
  dataObj.add("");
  dataObj.add("# 0 faces, 0 texture coords");
  dataObj.add("");
  dataObj.add("# End of File");
  dataObj.endSave(objFilePath + "/" + objFileName + "." + objFileType);
}

int countVertices(){
  int counter=0;
  for (int i=0;i<voxel.length;i++) {
    for (int j=0;j<voxel[i].length;j++) {
      for (int k=0;k<voxel[i][j].length;k++) {
        if(voxel[i][j][k].drawMe){
        counter++;
        }
      }
    }
  }
  return counter;
}